Iquod flag testing
IQuOD/wodpy pull request #39
Opened 2023-09-15 04:02 UTC by BecCowley

@BillMills 
There is one extra change not commented on in there. I've included code to read from the s3 Bucket. Maybe a better way to do that, and it's slow so it might not even be useful.
I was testing to see what I could do with reading from s3. Happy for input on that.

2023-12-13 16:37 UTC, BillMills requested changes
Thanks @BecCowley and sorry for the absurdly slow reply; I think you're on the right track here, but see comments inline.

2023-12-13 16:37 UTC, BillMills commented on wodpy/wodnc.py
> +            # if this is a file object from s3 bucket
Cool! Are there any public buckets I can point this at and watch it go? Should we add a usage example to the readme?

2023-12-13 16:37 UTC, BillMills commented on wodpy/wodnc.py
> +        # trim variable v to ust include the variable name left of any underscore:
This is the part of this PR I'm finding the most mysterious - iirc aren't things like QC variables named like `Temperature_origflag`? Why would we coerce this to just `Temperature`? Maybe I'm remembering wrong, please let me know what our goal with this change is.

2023-12-13 16:37 UTC, BillMills commented on wodpy/wodnc.py
> +            logging.warning(data_key + ' not level data.')
this seems much better, thanks - one petty point, can you make the logging warning here and on line 146 different, so users can tell which failure mode they fell into clearly.

2023-12-13 21:21 UTC, BecCowley commented on wodpy/wodnc.py
> +            # if this is a file object from s3 bucket
@BillMills, not yet, but will be I hope. I can send you a link to test bucket that Tim has created if you like?

2023-12-13 21:44 UTC, BecCowley commented on wodpy/wodnc.py
> +        # trim variable v to ust include the variable name left of any underscore:
Good question. I had to review! The reason:
if you want to get the variable 'Temperature_WODflag',  v+'row_size'  = Temperature_WODflag_row_size which doesn't exist. The variable we need is 'Temperature_row_size' which applies to all the Temperature* variables.

2023-12-13 22:05 UTC, BecCowley commented on wodpy/wodnc.py
> +            logging.warning(data_key + ' not level data.')
Have updated logging message, but then I commented it out as I don't think the information is useful (and could cause confusion). It is useful for debugging, though.

2023-12-18 17:41 UTC, BillMills commented on wodpy/wodnc.py
> +        # trim variable v to ust include the variable name left of any underscore:
Right!

2023-12-18 17:41 UTC, BillMills commented on wodpy/wodnc.py
> +            logging.warning(data_key + ' not level data.')
Sounds good.

2023-12-18 17:42 UTC, BillMills commented on wodpy/wodnc.py
> +            # if this is a file object from s3 bucket
Yes please. I suspect this is fine, but due diligence demands I at least try it once.

2023-12-18 22:15 UTC, BecCowley commented on wodpy/wodnc.py
> +            # if this is a file object from s3 bucket
Have sent the link via email.

2024-01-14 23:48 UTC, BillMills requested changes

2024-01-14 23:48 UTC, BillMills commented on wodpy/wodnc.py
> +            # if this is a file object from s3 bucket
OK - so intended usage is something like:

```
from wodpy import wodnc
import boto3, io

s3_client = boto3.client('s3')
s3_response_object = s3_client.get_object(Bucket='wodpynctest', Key='ocldb1570984477.6279_OSD.nc')
object_content = s3_response_object['Body'].read()
netcdf_bytes_io = io.BytesIO(object_content) 

r = wodnc.Ragged(netcdf_bytes_io). # this argument is a <class '_io.BytesIO'> object
p = wodnc.ncProfile(r, 0)
print(p.uid())
```

Is that what you had in mind, or something else? Also, I wonder if we're really winning much by getting involved with BytesIO streams here; if instead we just pass a bytes object into the `memory` argument of the `Dataset` constructor (ie delete your line 43 and just pass in `memory=filename` in 44), then both the following examples work:

```
from wodpy import wodnc
import boto3, io  
import requests

# example 1: boto without casting to BytesIO
s3_client = boto3.client('s3')
s3_response_object = s3_client.get_object(Bucket='wodpynctest', Key='ocldb1570984477.6279_OSD.nc')
object_content = s3_response_object['Body'].read()
r = wodnc.Ragged(object_content)
p = wodnc.ncProfile(r, 0)
print(p.uid())

# example 2: or just plain old requests if the netcdf file is publicly reachable
res = requests.get('https://wodpynctest.s3.amazonaws.com/ocldb1570984477.6279_OSD.nc')
r = wodnc.Ragged(res.content)
p = wodnc.ncProfile(r, 0)
print(p.uid())
```

These feel a bit simpler to me, but maybe I'm failing to understand your original intention. In any case, can you please add a minimal usage example to the README under the "IQuOD netCDF data" section so folks can use this easily, since I fiddled around for a while here determining intended usage. Thanks, we'll be good to merge once that's in place!

2024-02-13 01:17 UTC, BecCowley commented on wodpy/wodnc.py
> +            # if this is a file object from s3 bucket
@BillMills I am not sure what the best way is to do this. I was experimenting at accessing the files directly in the cloud, rather than downloading. It turns out to be particularly slow and therefore, we downloaded files instead. Perhaps remove this change from the PR until such time as we need to access AWS files. I don't know enough about how best to do it at this stage.

2024-02-13 05:39 UTC, BillMills commented on wodpy/wodnc.py
> +            # if this is a file object from s3 bucket
Broadly the way to do this I guess would be to stream the netCDF from S3, something like:

```
res = requests.get('https://wodpynctest.s3.amazonaws.com/ocldb1570984477.6279_OSD.nc')
self.rootgrp = Dataset('dsstream.nc', memory=res.content)
```
let me play with this for a couple of days and think about if it's actually doing what we want, I think your goal of efficient S3 reads is a good one. Once I have something I'm happy with, I'll amend here, update the docs, and merge, I'm shooting for before OSM.

2024-02-14 18:43 UTC, BillMills commented on wodpy/wodnc.py
> +            # if this is a file object from s3 bucket
OK, as I feared, `requests.get` and any full `.read()` of the boto S3 object just immediately sucks down the whole file, which doesn't confer any advantage over just downloading the .nc files. wodpy isn't setting out to be a download manager, so I think we'll do as you say and drop this for now; I'll amend and merge later today. It's still an interesting idea though, but perhaps better pursued later as .zarr support if WOD chooses to go in that direction.

2024-02-14 19:28 UTC, merged

2024-02-14 20:12 UTC, BillMills commented
Thanks again for this @BecCowley and apologies for the slow start; this has been merged and prereleased as a beta, install via `pip install wodpy==2.0.0b1`.